<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.7.13-SNAPSHOT">
]
>

<object class="weka.experiment.RemoteExperiment" name="__root__" version="3.7.13-SNAPSHOT">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.meta.FilteredClassifier" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.BarcodingNumericToBinary -R 5,6</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.BarcodingNumericToBinary -R 6</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">30</object>
            <object class="java.lang.String" name="2">-K</object>
            <object class="java.lang.String" name="3">0</object>
            <object class="java.lang.String" name="4">-S</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-num-slots</object>
            <object class="java.lang.String" name="7">4</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.supervised.attribute.Discretize -R first-last -precision 6</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.supervised.attribute.Discretize -D -R first-last -precision 6</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.trees.RandomForest</object>
            <object class="java.lang.String" name="4">--</object>
            <object class="java.lang.String" name="5">-I</object>
            <object class="java.lang.String" name="6">30</object>
            <object class="java.lang.String" name="7">-K</object>
            <object class="java.lang.String" name="8">0</object>
            <object class="java.lang.String" name="9">-S</object>
            <object class="java.lang.String" name="10">1</object>
            <object class="java.lang.String" name="11">-num-slots</object>
            <object class="java.lang.String" name="12">4</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.Discretize -F -B 10 -M -1.0 -R first-last</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.Discretize -D -F -B 10 -M -1.0 -R first-last</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.trees.RandomForest</object>
            <object class="java.lang.String" name="4">--</object>
            <object class="java.lang.String" name="5">-I</object>
            <object class="java.lang.String" name="6">30</object>
            <object class="java.lang.String" name="7">-K</object>
            <object class="java.lang.String" name="8">0</object>
            <object class="java.lang.String" name="9">-S</object>
            <object class="java.lang.String" name="10">1</object>
            <object class="java.lang.String" name="11">-num-slots</object>
            <object class="java.lang.String" name="12">4</object>
         </object>
      </object>
   </object>
   <object class="boolean" name="splitByDataSet" primitive="yes">true</object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">/research/repository/cjb60/output/ibol.species.seq150.k11.arff</object>
      <object class="java.io.File" name="1">/research/repository/cjb60/output/ibol.species.seq150.k12.arff</object>
      <object class="java.io.File" name="2">/research/repository/cjb60/output/ibol.species.seq150.k13.arff</object>
      <object class="java.io.File" name="3">/research/repository/cjb60/output/ibol.species.seq150.k14.arff</object>
      <object class="java.io.File" name="4">/research/repository/cjb60/output/ibol.species.seq150.k15.arff</object>
      <object class="java.io.File" name="5">/research/repository/cjb60/output/ibol.species.seq150.k16.arff</object>
      <object class="java.io.File" name="6">/research/repository/cjb60/output/ibol.species.seq300.k11.arff</object>
      <object class="java.io.File" name="7">/research/repository/cjb60/output/ibol.species.seq300.k12.arff</object>
      <object class="java.io.File" name="8">/research/repository/cjb60/output/ibol.species.seq300.k13.arff</object>
      <object class="java.io.File" name="9">/research/repository/cjb60/output/ibol.species.seq300.k14.arff</object>
      <object class="java.io.File" name="10">/research/repository/cjb60/output/ibol.species.seq300.k15.arff</object>
      <object class="java.io.File" name="11">/research/repository/cjb60/output/ibol.species.seq300.k16.arff</object>
      <object class="java.io.File" name="12">/research/repository/cjb60/output/ibol.species.seq450.k11.arff</object>
      <object class="java.io.File" name="13">/research/repository/cjb60/output/ibol.species.seq450.k12.arff</object>
      <object class="java.io.File" name="14">/research/repository/cjb60/output/ibol.species.seq450.k13.arff</object>
      <object class="java.io.File" name="15">/research/repository/cjb60/output/ibol.species.seq450.k14.arff</object>
      <object class="java.io.File" name="16">/research/repository/cjb60/output/ibol.species.seq450.k15.arff</object>
      <object class="java.io.File" name="17">/research/repository/cjb60/output/ibol.species.seq450.k16.arff</object>
      <object class="java.io.File" name="18">/research/repository/cjb60/output/ibol.species.seq600.k11.arff</object>
      <object class="java.io.File" name="19">/research/repository/cjb60/output/ibol.species.seq600.k12.arff</object>
      <object class="java.io.File" name="20">/research/repository/cjb60/output/ibol.species.seq600.k13.arff</object>
      <object class="java.io.File" name="21">/research/repository/cjb60/output/ibol.species.seq600.k14.arff</object>
      <object class="java.io.File" name="22">/research/repository/cjb60/output/ibol.species.seq600.k15.arff</object>
      <object class="java.io.File" name="23">/research/repository/cjb60/output/ibol.species.seq600.k16.arff</object>
      <object class="java.io.File" name="24">/research/repository/cjb60/output/res50k.family.seq150.k11.arff</object>
      <object class="java.io.File" name="25">/research/repository/cjb60/output/res50k.family.seq150.k12.arff</object>
      <object class="java.io.File" name="26">/research/repository/cjb60/output/res50k.family.seq150.k13.arff</object>
      <object class="java.io.File" name="27">/research/repository/cjb60/output/res50k.family.seq150.k14.arff</object>
      <object class="java.io.File" name="28">/research/repository/cjb60/output/res50k.family.seq150.k15.arff</object>
      <object class="java.io.File" name="29">/research/repository/cjb60/output/res50k.family.seq150.k16.arff</object>
      <object class="java.io.File" name="30">/research/repository/cjb60/output/res50k.family.seq300.k11.arff</object>
      <object class="java.io.File" name="31">/research/repository/cjb60/output/res50k.family.seq300.k12.arff</object>
      <object class="java.io.File" name="32">/research/repository/cjb60/output/res50k.family.seq300.k13.arff</object>
      <object class="java.io.File" name="33">/research/repository/cjb60/output/res50k.family.seq300.k14.arff</object>
      <object class="java.io.File" name="34">/research/repository/cjb60/output/res50k.family.seq300.k15.arff</object>
      <object class="java.io.File" name="35">/research/repository/cjb60/output/res50k.family.seq300.k16.arff</object>
      <object class="java.io.File" name="36">/research/repository/cjb60/output/res50k.family.seq450.k11.arff</object>
      <object class="java.io.File" name="37">/research/repository/cjb60/output/res50k.family.seq450.k12.arff</object>
      <object class="java.io.File" name="38">/research/repository/cjb60/output/res50k.family.seq450.k13.arff</object>
      <object class="java.io.File" name="39">/research/repository/cjb60/output/res50k.family.seq450.k14.arff</object>
      <object class="java.io.File" name="40">/research/repository/cjb60/output/res50k.family.seq450.k15.arff</object>
      <object class="java.io.File" name="41">/research/repository/cjb60/output/res50k.family.seq450.k16.arff</object>
      <object class="java.io.File" name="42">/research/repository/cjb60/output/res50k.family.seq600.k11.arff</object>
      <object class="java.io.File" name="43">/research/repository/cjb60/output/res50k.family.seq600.k12.arff</object>
      <object class="java.io.File" name="44">/research/repository/cjb60/output/res50k.family.seq600.k13.arff</object>
      <object class="java.io.File" name="45">/research/repository/cjb60/output/res50k.family.seq600.k14.arff</object>
      <object class="java.io.File" name="46">/research/repository/cjb60/output/res50k.family.seq600.k15.arff</object>
      <object class="java.io.File" name="47">/research/repository/cjb60/output/res50k.family.seq600.k16.arff</object>
      <object class="java.io.File" name="48">/research/repository/cjb60/output/res50k.genus.seq150.k11.arff</object>
      <object class="java.io.File" name="49">/research/repository/cjb60/output/res50k.genus.seq150.k12.arff</object>
      <object class="java.io.File" name="50">/research/repository/cjb60/output/res50k.genus.seq150.k13.arff</object>
      <object class="java.io.File" name="51">/research/repository/cjb60/output/res50k.genus.seq150.k14.arff</object>
      <object class="java.io.File" name="52">/research/repository/cjb60/output/res50k.genus.seq150.k15.arff</object>
      <object class="java.io.File" name="53">/research/repository/cjb60/output/res50k.genus.seq150.k16.arff</object>
      <object class="java.io.File" name="54">/research/repository/cjb60/output/res50k.genus.seq300.k11.arff</object>
      <object class="java.io.File" name="55">/research/repository/cjb60/output/res50k.genus.seq300.k12.arff</object>
      <object class="java.io.File" name="56">/research/repository/cjb60/output/res50k.genus.seq300.k13.arff</object>
      <object class="java.io.File" name="57">/research/repository/cjb60/output/res50k.genus.seq300.k14.arff</object>
      <object class="java.io.File" name="58">/research/repository/cjb60/output/res50k.genus.seq300.k15.arff</object>
      <object class="java.io.File" name="59">/research/repository/cjb60/output/res50k.genus.seq300.k16.arff</object>
      <object class="java.io.File" name="60">/research/repository/cjb60/output/res50k.genus.seq450.k11.arff</object>
      <object class="java.io.File" name="61">/research/repository/cjb60/output/res50k.genus.seq450.k12.arff</object>
      <object class="java.io.File" name="62">/research/repository/cjb60/output/res50k.genus.seq450.k13.arff</object>
      <object class="java.io.File" name="63">/research/repository/cjb60/output/res50k.genus.seq450.k14.arff</object>
      <object class="java.io.File" name="64">/research/repository/cjb60/output/res50k.genus.seq450.k15.arff</object>
      <object class="java.io.File" name="65">/research/repository/cjb60/output/res50k.genus.seq450.k16.arff</object>
      <object class="java.io.File" name="66">/research/repository/cjb60/output/res50k.genus.seq600.k11.arff</object>
      <object class="java.io.File" name="67">/research/repository/cjb60/output/res50k.genus.seq600.k12.arff</object>
      <object class="java.io.File" name="68">/research/repository/cjb60/output/res50k.genus.seq600.k13.arff</object>
      <object class="java.io.File" name="69">/research/repository/cjb60/output/res50k.genus.seq600.k14.arff</object>
      <object class="java.io.File" name="70">/research/repository/cjb60/output/res50k.genus.seq600.k15.arff</object>
      <object class="java.io.File" name="71">/research/repository/cjb60/output/res50k.genus.seq600.k16.arff</object>
   </object>
   <object class="javax.swing.DefaultListModel" name="remoteHosts">
      <object class="java.lang.String" name="0">ml64-20.cms.waikato.ac.nz:9000</object>
      <object class="java.lang.String" name="1">ml64-21.cms.waikato.ac.nz:9000</object>
      <object class="java.lang.String" name="2">ml64-22.cms.waikato.ac.nz:9000</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">1</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">3</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.DatabaseResultListener" name="resultListener">
      <object class="java.lang.String" name="keywordsMaskChar">_</object>
      <object class="java.lang.String" name="cacheKeyName"/>
      <object class="boolean" name="debug" primitive="yes">false</object>
      <object class="java.lang.String" name="password"/>
      <object class="java.lang.String" name="keywords">ABS,ACOS,ALIAS,ALL,ALTER,ASCII,ASIN,ATAN,ATAN2,AUTOCOMMIT,BITAND,BITOR,BIT_LENGTH,CACHED,CALL,CASEWHEN,CEILING,CHAR,CHAR_LENGTH,CHECKPOINT,COALESCE,COLLATION,COMMIT,CONCAT,CONNECT,CONVERT,COS,COT,CREATE,CURDATE,CURRENT_DATE,CURRENT_TIME,CURRENT_TIMESTAMP,CURRENT_USER,CURTIME,DATABASE,DAYNAME,DAYOFMONTH,DAYOFWEEK,DAYOFYEAR,DEFRAG,DEGREES,DELAY,DELETE,DIFFERENCE,DISCONNECT,DISTINCT,DROP,EXCEPT,EXP,EXPLAIN,EXTRACT,FLOOR,FROM,GRANT,GROUPBY,HAVING,HEXTORAW,HOUR,IDENTITY,IFNULL,IGNORECASE,INDEX,INITIAL,INSERT,INTEGRITY,INTERSECT,INTO,LCASE,LEFT,LENGTH,LIMIT,LOCATE,LOG,LOG10,LOGSIZE,LOWER,LTRIM,MAXROWS,MINUS,MINUTE,MOD,MONTH,MONTHNAME,NOW,NULLIF,OCTET_LENGTH,OFFSET,ORDERBY,PASSWORD,PI,PLAN,POWER,PROPERTY,QUARTER,RADIANS,RAND,RAWTOHEX,READONLY,REFERENTIAL,REPEAT,REPLACE,REVOKE,RIGHT,ROLE,ROLLBACK,ROUND,ROUNDMAGIC,RTRIM,SAVEPOINT,SCHEMA,SCRIPT,SCRIPTFORMAT,SECOND,SELECT,SEQUENCE,SET,SHUTDOWN,SIGN,SIN,SOUNDEX,SOURCE,SPACE,SQRT,SUBSTR,SUBSTRING,TABLE,TAN,TEMP,TEXT,TOP,TRIGGER,TRUNCATE,UCASE,UNION,UPDATE,UPPER,USER,VIEW,WEEK,WHERE,WRITE,YEAR</object>
      <object class="java.lang.String" name="databaseURL">jdbc:hsqldb:hsql://ml64-22.cms.waikato.ac.nz</object>
      <object class="java.lang.String" name="username">sa</object>
   </object>
   <object class="weka.experiment.Experiment" name="baseExperiment">
      <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
         <object class="weka.classifiers.meta.FilteredClassifier" name="0">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-F</object>
               <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.BarcodingNumericToBinary -R 5,6</object>
               <object class="java.lang.String" name="2">-W</object>
               <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
            </object>
         </object>
         <object class="weka.classifiers.meta.FilteredClassifier" name="1">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-F</object>
               <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.BarcodingNumericToBinary -R 6</object>
               <object class="java.lang.String" name="2">-W</object>
               <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
            </object>
         </object>
         <object class="weka.classifiers.trees.RandomForest" name="2">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-I</object>
               <object class="java.lang.String" name="1">30</object>
               <object class="java.lang.String" name="2">-K</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-S</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">-num-slots</object>
               <object class="java.lang.String" name="7">4</object>
            </object>
         </object>
         <object class="weka.classifiers.meta.FilteredClassifier" name="3">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-F</object>
               <object class="java.lang.String" name="1">weka.filters.supervised.attribute.Discretize -R first-last -precision 6</object>
               <object class="java.lang.String" name="2">-W</object>
               <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
            </object>
         </object>
         <object class="weka.classifiers.meta.FilteredClassifier" name="4">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-F</object>
               <object class="java.lang.String" name="1">weka.filters.supervised.attribute.Discretize -D -R first-last -precision 6</object>
               <object class="java.lang.String" name="2">-W</object>
               <object class="java.lang.String" name="3">weka.classifiers.trees.RandomForest</object>
               <object class="java.lang.String" name="4">--</object>
               <object class="java.lang.String" name="5">-I</object>
               <object class="java.lang.String" name="6">30</object>
               <object class="java.lang.String" name="7">-K</object>
               <object class="java.lang.String" name="8">0</object>
               <object class="java.lang.String" name="9">-S</object>
               <object class="java.lang.String" name="10">1</object>
               <object class="java.lang.String" name="11">-num-slots</object>
               <object class="java.lang.String" name="12">4</object>
            </object>
         </object>
         <object class="weka.classifiers.meta.FilteredClassifier" name="5">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-F</object>
               <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.Discretize -F -B 10 -M -1.0 -R first-last</object>
               <object class="java.lang.String" name="2">-W</object>
               <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
            </object>
         </object>
         <object class="weka.classifiers.meta.FilteredClassifier" name="6">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-F</object>
               <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.Discretize -D -F -B 10 -M -1.0 -R first-last</object>
               <object class="java.lang.String" name="2">-W</object>
               <object class="java.lang.String" name="3">weka.classifiers.trees.RandomForest</object>
               <object class="java.lang.String" name="4">--</object>
               <object class="java.lang.String" name="5">-I</object>
               <object class="java.lang.String" name="6">30</object>
               <object class="java.lang.String" name="7">-K</object>
               <object class="java.lang.String" name="8">0</object>
               <object class="java.lang.String" name="9">-S</object>
               <object class="java.lang.String" name="10">1</object>
               <object class="java.lang.String" name="11">-num-slots</object>
               <object class="java.lang.String" name="12">4</object>
            </object>
         </object>
      </object>
      <object class="javax.swing.DefaultListModel" name="datasets">
         <object class="java.io.File" name="0">/research/repository/cjb60/output/ibol.species.seq150.k11.arff</object>
         <object class="java.io.File" name="1">/research/repository/cjb60/output/ibol.species.seq150.k12.arff</object>
         <object class="java.io.File" name="2">/research/repository/cjb60/output/ibol.species.seq150.k13.arff</object>
         <object class="java.io.File" name="3">/research/repository/cjb60/output/ibol.species.seq150.k14.arff</object>
         <object class="java.io.File" name="4">/research/repository/cjb60/output/ibol.species.seq150.k15.arff</object>
         <object class="java.io.File" name="5">/research/repository/cjb60/output/ibol.species.seq150.k16.arff</object>
         <object class="java.io.File" name="6">/research/repository/cjb60/output/ibol.species.seq300.k11.arff</object>
         <object class="java.io.File" name="7">/research/repository/cjb60/output/ibol.species.seq300.k12.arff</object>
         <object class="java.io.File" name="8">/research/repository/cjb60/output/ibol.species.seq300.k13.arff</object>
         <object class="java.io.File" name="9">/research/repository/cjb60/output/ibol.species.seq300.k14.arff</object>
         <object class="java.io.File" name="10">/research/repository/cjb60/output/ibol.species.seq300.k15.arff</object>
         <object class="java.io.File" name="11">/research/repository/cjb60/output/ibol.species.seq300.k16.arff</object>
         <object class="java.io.File" name="12">/research/repository/cjb60/output/ibol.species.seq450.k11.arff</object>
         <object class="java.io.File" name="13">/research/repository/cjb60/output/ibol.species.seq450.k12.arff</object>
         <object class="java.io.File" name="14">/research/repository/cjb60/output/ibol.species.seq450.k13.arff</object>
         <object class="java.io.File" name="15">/research/repository/cjb60/output/ibol.species.seq450.k14.arff</object>
         <object class="java.io.File" name="16">/research/repository/cjb60/output/ibol.species.seq450.k15.arff</object>
         <object class="java.io.File" name="17">/research/repository/cjb60/output/ibol.species.seq450.k16.arff</object>
         <object class="java.io.File" name="18">/research/repository/cjb60/output/ibol.species.seq600.k11.arff</object>
         <object class="java.io.File" name="19">/research/repository/cjb60/output/ibol.species.seq600.k12.arff</object>
         <object class="java.io.File" name="20">/research/repository/cjb60/output/ibol.species.seq600.k13.arff</object>
         <object class="java.io.File" name="21">/research/repository/cjb60/output/ibol.species.seq600.k14.arff</object>
         <object class="java.io.File" name="22">/research/repository/cjb60/output/ibol.species.seq600.k15.arff</object>
         <object class="java.io.File" name="23">/research/repository/cjb60/output/ibol.species.seq600.k16.arff</object>
         <object class="java.io.File" name="24">/research/repository/cjb60/output/res50k.family.seq150.k11.arff</object>
         <object class="java.io.File" name="25">/research/repository/cjb60/output/res50k.family.seq150.k12.arff</object>
         <object class="java.io.File" name="26">/research/repository/cjb60/output/res50k.family.seq150.k13.arff</object>
         <object class="java.io.File" name="27">/research/repository/cjb60/output/res50k.family.seq150.k14.arff</object>
         <object class="java.io.File" name="28">/research/repository/cjb60/output/res50k.family.seq150.k15.arff</object>
         <object class="java.io.File" name="29">/research/repository/cjb60/output/res50k.family.seq150.k16.arff</object>
         <object class="java.io.File" name="30">/research/repository/cjb60/output/res50k.family.seq300.k11.arff</object>
         <object class="java.io.File" name="31">/research/repository/cjb60/output/res50k.family.seq300.k12.arff</object>