<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.7.12-SNAPSHOT">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.7.12-SNAPSHOT">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.bayes.NaiveBayes" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options"/>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">30</object>
            <object class="java.lang.String" name="2">-K</object>
            <object class="java.lang.String" name="3">0</object>
            <object class="java.lang.String" name="4">-S</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-num-slots</object>
            <object class="java.lang.String" name="7">4</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.supervised.attribute.Discretize -R first-last -precision 6</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.supervised.attribute.Discretize -R first-last -precision 6</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.trees.RandomForest</object>
            <object class="java.lang.String" name="4">--</object>
            <object class="java.lang.String" name="5">-I</object>
            <object class="java.lang.String" name="6">30</object>
            <object class="java.lang.String" name="7">-K</object>
            <object class="java.lang.String" name="8">0</object>
            <object class="java.lang.String" name="9">-S</object>
            <object class="java.lang.String" name="10">1</object>
            <object class="java.lang.String" name="11">-num-slots</object>
            <object class="java.lang.String" name="12">4</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.Discretize -O -B 10 -M -1.0 -R first-last</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.Discretize -O -B 10 -M -1.0 -R first-last</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.trees.RandomForest</object>
            <object class="java.lang.String" name="4">--</object>
            <object class="java.lang.String" name="5">-I</object>
            <object class="java.lang.String" name="6">30</object>
            <object class="java.lang.String" name="7">-K</object>
            <object class="java.lang.String" name="8">0</object>
            <object class="java.lang.String" name="9">-S</object>
            <object class="java.lang.String" name="10">1</object>
            <object class="java.lang.String" name="11">-num-slots</object>
            <object class="java.lang.String" name="12">4</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">output-mix/ibol.species.seq150.k11.arff</object>
      <object class="java.io.File" name="1">output-mix/ibol.species.seq150.k12.arff</object>
      <object class="java.io.File" name="2">output-mix/ibol.species.seq150.k13.arff</object>
      <object class="java.io.File" name="3">output-mix/ibol.species.seq150.k14.arff</object>
      <object class="java.io.File" name="4">output-mix/ibol.species.seq150.k15.arff</object>
      <object class="java.io.File" name="5">output-mix/ibol.species.seq150.k16.arff</object>
      <object class="java.io.File" name="6">output-mix/ibol.species.seq300.k11.arff</object>
      <object class="java.io.File" name="7">output-mix/ibol.species.seq300.k12.arff</object>
      <object class="java.io.File" name="8">output-mix/ibol.species.seq300.k13.arff</object>
      <object class="java.io.File" name="9">output-mix/ibol.species.seq300.k14.arff</object>
      <object class="java.io.File" name="10">output-mix/ibol.species.seq300.k15.arff</object>
      <object class="java.io.File" name="11">output-mix/ibol.species.seq300.k16.arff</object>
      <object class="java.io.File" name="12">output-mix/ibol.species.seq450.k11.arff</object>
      <object class="java.io.File" name="13">output-mix/ibol.species.seq450.k12.arff</object>
      <object class="java.io.File" name="14">output-mix/ibol.species.seq450.k13.arff</object>
      <object class="java.io.File" name="15">output-mix/ibol.species.seq450.k14.arff</object>
      <object class="java.io.File" name="16">output-mix/ibol.species.seq450.k15.arff</object>
      <object class="java.io.File" name="17">output-mix/ibol.species.seq450.k16.arff</object>
      <object class="java.io.File" name="18">output-mix/ibol.species.seq600.k11.arff</object>
      <object class="java.io.File" name="19">output-mix/ibol.species.seq600.k12.arff</object>
      <object class="java.io.File" name="20">output-mix/ibol.species.seq600.k13.arff</object>
      <object class="java.io.File" name="21">output-mix/ibol.species.seq600.k14.arff</object>
      <object class="java.io.File" name="22">output-mix/ibol.species.seq600.k15.arff</object>
      <object class="java.io.File" name="23">output-mix/ibol.species.seq600.k16.arff</object>
      <object class="java.io.File" name="24">output-mix/res50k.family.seq150.k11.arff</object>
      <object class="java.io.File" name="25">output-mix/res50k.family.seq150.k12.arff</object>
      <object class="java.io.File" name="26">output-mix/res50k.family.seq150.k13.arff</object>
      <object class="java.io.File" name="27">output-mix/res50k.family.seq150.k14.arff</object>
      <object class="java.io.File" name="28">output-mix/res50k.family.seq150.k15.arff</object>
      <object class="java.io.File" name="29">output-mix/res50k.family.seq150.k16.arff</object>
      <object class="java.io.File" name="30">output-mix/res50k.family.seq300.k11.arff</object>
      <object class="java.io.File" name="31">output-mix/res50k.family.seq300.k12.arff</object>
      <object class="java.io.File" name="32">output-mix/res50k.family.seq300.k13.arff</object>
      <object class="java.io.File" name="33">output-mix/res50k.family.seq300.k14.arff</object>
      <object class="java.io.File" name="34">output-mix/res50k.family.seq300.k15.arff</object>
      <object class="java.io.File" name="35">output-mix/res50k.family.seq300.k16.arff</object>
      <object class="java.io.File" name="36">output-mix/res50k.family.seq450.k11.arff</object>
      <object class="java.io.File" name="37">output-mix/res50k.family.seq450.k12.arff</object>
      <object class="java.io.File" name="38">output-mix/res50k.family.seq450.k13.arff</object>
      <object class="java.io.File" name="39">output-mix/res50k.family.seq450.k14.arff</object>
      <object class="java.io.File" name="40">output-mix/res50k.family.seq450.k15.arff</object>
      <object class="java.io.File" name="41">output-mix/res50k.family.seq450.k16.arff</object>
      <object class="java.io.File" name="42">output-mix/res50k.family.seq600.k11.arff</object>
      <object class="java.io.File" name="43">output-mix/res50k.family.seq600.k12.arff</object>
      <object class="java.io.File" name="44">output-mix/res50k.family.seq600.k13.arff</object>
      <object class="java.io.File" name="45">output-mix/res50k.family.seq600.k14.arff</object>
      <object class="java.io.File" name="46">output-mix/res50k.family.seq600.k15.arff</object>
      <object class="java.io.File" name="47">output-mix/res50k.family.seq600.k16.arff</object>
      <object class="java.io.File" name="48">output-mix/res50k.genus.seq150.k11.arff</object>
      <object class="java.io.File" name="49">output-mix/res50k.genus.seq150.k12.arff</object>
      <object class="java.io.File" name="50">output-mix/res50k.genus.seq150.k13.arff</object>
      <object class="java.io.File" name="51">output-mix/res50k.genus.seq150.k14.arff</object>
      <object class="java.io.File" name="52">output-mix/res50k.genus.seq150.k15.arff</object>
      <object class="java.io.File" name="53">output-mix/res50k.genus.seq150.k16.arff</object>
      <object class="java.io.File" name="54">output-mix/res50k.genus.seq300.k11.arff</object>
      <object class="java.io.File" name="55">output-mix/res50k.genus.seq300.k12.arff</object>
      <object class="java.io.File" name="56">output-mix/res50k.genus.seq300.k13.arff</object>
      <object class="java.io.File" name="57">output-mix/res50k.genus.seq300.k14.arff</object>
      <object class="java.io.File" name="58">output-mix/res50k.genus.seq300.k15.arff</object>
      <object class="java.io.File" name="59">output-mix/res50k.genus.seq300.k16.arff</object>
      <object class="java.io.File" name="60">output-mix/res50k.genus.seq450.k11.arff</object>
      <object class="java.io.File" name="61">output-mix/res50k.genus.seq450.k12.arff</object>
      <object class="java.io.File" name="62">output-mix/res50k.genus.seq450.k13.arff</object>
      <object class="java.io.File" name="63">output-mix/res50k.genus.seq450.k14.arff</object>
      <object class="java.io.File" name="64">output-mix/res50k.genus.seq450.k15.arff</object>
      <object class="java.io.File" name="65">output-mix/res50k.genus.seq450.k16.arff</object>
      <object class="java.io.File" name="66">output-mix/res50k.genus.seq600.k11.arff</object>
      <object class="java.io.File" name="67">output-mix/res50k.genus.seq600.k12.arff</object>
      <object class="java.io.File" name="68">output-mix/res50k.genus.seq600.k13.arff</object>
      <object class="java.io.File" name="69">output-mix/res50k.genus.seq600.k14.arff</object>
      <object class="java.io.File" name="70">output-mix/res50k.genus.seq600.k15.arff</object>
      <object class="java.io.File" name="71">output-mix/res50k.genus.seq600.k16.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">1</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">3</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">new-result.arff</object>
      </object>
      <object class="java.io.File" name="outputFile">results/new-result.arff</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">true</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
