<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.7.12-SNAPSHOT">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.7.12-SNAPSHOT">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.meta.FilteredClassifier" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.unsupervised.attribute.Discretize -F -B 10 -M -1.0 -R first-last</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">30</object>
            <object class="java.lang.String" name="2">-K</object>
            <object class="java.lang.String" name="3">0</object>
            <object class="java.lang.String" name="4">-S</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-num-slots</object>
            <object class="java.lang.String" name="7">4</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">output/ibol.species.seq150.k11.arff</object>
      <object class="java.io.File" name="1">output/ibol.species.seq150.k12.arff</object>
      <object class="java.io.File" name="2">output/ibol.species.seq150.k13.arff</object>
      <object class="java.io.File" name="3">output/ibol.species.seq150.k14.arff</object>
      <object class="java.io.File" name="4">output/ibol.species.seq150.k15.arff</object>
      <object class="java.io.File" name="5">output/ibol.species.seq150.k16.arff</object>
      <object class="java.io.File" name="6">output/ibol.species.seq300.k11.arff</object>
      <object class="java.io.File" name="7">output/ibol.species.seq300.k12.arff</object>
      <object class="java.io.File" name="8">output/ibol.species.seq300.k13.arff</object>
      <object class="java.io.File" name="9">output/ibol.species.seq300.k14.arff</object>
      <object class="java.io.File" name="10">output/ibol.species.seq300.k15.arff</object>
      <object class="java.io.File" name="11">output/ibol.species.seq300.k16.arff</object>
      <object class="java.io.File" name="12">output/ibol.species.seq450.k11.arff</object>
      <object class="java.io.File" name="13">output/ibol.species.seq450.k12.arff</object>
      <object class="java.io.File" name="14">output/ibol.species.seq450.k13.arff</object>
      <object class="java.io.File" name="15">output/ibol.species.seq450.k14.arff</object>
      <object class="java.io.File" name="16">output/ibol.species.seq450.k15.arff</object>
      <object class="java.io.File" name="17">output/ibol.species.seq450.k16.arff</object>
      <object class="java.io.File" name="18">output/ibol.species.seq600.k11.arff</object>
      <object class="java.io.File" name="19">output/ibol.species.seq600.k12.arff</object>
      <object class="java.io.File" name="20">output/ibol.species.seq600.k13.arff</object>
      <object class="java.io.File" name="21">output/ibol.species.seq600.k14.arff</object>
      <object class="java.io.File" name="22">output/ibol.species.seq600.k15.arff</object>
      <object class="java.io.File" name="23">output/ibol.species.seq600.k16.arff</object>
      <object class="java.io.File" name="24">output/res50k.family.seq150.k11.arff</object>
      <object class="java.io.File" name="25">output/res50k.family.seq150.k12.arff</object>
      <object class="java.io.File" name="26">output/res50k.family.seq150.k13.arff</object>
      <object class="java.io.File" name="27">output/res50k.family.seq150.k14.arff</object>
      <object class="java.io.File" name="28">output/res50k.family.seq150.k15.arff</object>
      <object class="java.io.File" name="29">output/res50k.family.seq150.k16.arff</object>
      <object class="java.io.File" name="30">output/res50k.family.seq300.k11.arff</object>
      <object class="java.io.File" name="31">output/res50k.family.seq300.k12.arff</object>
      <object class="java.io.File" name="32">output/res50k.family.seq300.k13.arff</object>
      <object class="java.io.File" name="33">output/res50k.family.seq300.k14.arff</object>
      <object class="java.io.File" name="34">output/res50k.family.seq300.k15.arff</object>
      <object class="java.io.File" name="35">output/res50k.family.seq300.k16.arff</object>
      <object class="java.io.File" name="36">output/res50k.family.seq450.k11.arff</object>
      <object class="java.io.File" name="37">output/res50k.family.seq450.k12.arff</object>
      <object class="java.io.File" name="38">output/res50k.family.seq450.k13.arff</object>
      <object class="java.io.File" name="39">output/res50k.family.seq450.k14.arff</object>
      <object class="java.io.File" name="40">output/res50k.family.seq450.k15.arff</object>
      <object class="java.io.File" name="41">output/res50k.family.seq450.k16.arff</object>
      <object class="java.io.File" name="42">output/res50k.family.seq600.k11.arff</object>
      <object class="java.io.File" name="43">output/res50k.family.seq600.k12.arff</object>
      <object class="java.io.File" name="44">output/res50k.family.seq600.k13.arff</object>
      <object class="java.io.File" name="45">output/res50k.family.seq600.k14.arff</object>
      <object class="java.io.File" name="46">output/res50k.family.seq600.k15.arff</object>
      <object class="java.io.File" name="47">output/res50k.family.seq600.k16.arff</object>
      <object class="java.io.File" name="48">output/res50k.genus.seq150.k11.arff</object>
      <object class="java.io.File" name="49">output/res50k.genus.seq150.k12.arff</object>
      <object class="java.io.File" name="50">output/res50k.genus.seq150.k13.arff</object>
      <object class="java.io.File" name="51">output/res50k.genus.seq150.k14.arff</object>
      <object class="java.io.File" name="52">output/res50k.genus.seq150.k15.arff</object>
      <object class="java.io.File" name="53">output/res50k.genus.seq150.k16.arff</object>
      <object class="java.io.File" name="54">output/res50k.genus.seq300.k11.arff</object>
      <object class="java.io.File" name="55">output/res50k.genus.seq300.k12.arff</object>
      <object class="java.io.File" name="56">output/res50k.genus.seq300.k13.arff</object>
      <object class="java.io.File" name="57">output/res50k.genus.seq300.k14.arff</object>
      <object class="java.io.File" name="58">output/res50k.genus.seq300.k15.arff</object>
      <object class="java.io.File" name="59">output/res50k.genus.seq300.k16.arff</object>
      <object class="java.io.File" name="60">output/res50k.genus.seq450.k11.arff</object>
      <object class="java.io.File" name="61">output/res50k.genus.seq450.k12.arff</object>
      <object class="java.io.File" name="62">output/res50k.genus.seq450.k13.arff</object>
      <object class="java.io.File" name="63">output/res50k.genus.seq450.k14.arff</object>
      <object class="java.io.File" name="64">output/res50k.genus.seq450.k15.arff</object>
      <object class="java.io.File" name="65">output/res50k.genus.seq450.k16.arff</object>
      <object class="java.io.File" name="66">output/res50k.genus.seq600.k11.arff</object>
      <object class="java.io.File" name="67">output/res50k.genus.seq600.k12.arff</object>
      <object class="java.io.File" name="68">output/res50k.genus.seq600.k13.arff</object>
      <object class="java.io.File" name="69">output/res50k.genus.seq600.k14.arff</object>
      <object class="java.io.File" name="70">output/res50k.genus.seq600.k15.arff</object>
      <object class="java.io.File" name="71">output/res50k.genus.seq600.k16.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">1</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">3</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.CSVResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">vary-k-bigger-15-ud-result.csv</object>
      </object>
      <object class="java.io.File" name="outputFile">results/vary-k-bigger-15-ud-result.csv</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">true</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
